### ISSUE TITLE
Is this compatible on T2?

### ISSUE THREAD

**Issue by johnnyman727** [Frijol/PIR#4]
Can you update the instructions on how to use this with T2?

**Comment by davidfekke** [comment]
John,

You should be able to use the pins in one of the ports (A, B). Most of the pins in the ports are GPIO. You can get a list by looking at the .pins array. You should be able to use tessel.port.A.pin[0] as an example.

**Comment by johnnyman727** [comment]
Thanks @davidfekke! It would be great if @Frijol could update the README as well.

**Comment by davidfekke** [comment]
Make a pull request. Unfortunately she is abroad, and has limited access to the internet right now.

**Comment by ahetawal** [comment]
@davidfekke Am planning to use this with my Tessel2. But have a question about how to get the power supply setup for the PIR sensor on Tessel2, as in Tessel1 there was a 5V supply pin present but not with 2. 
How do I power this sensor in t2.

Thanks again

**Comment by johnnyman727** [comment]
@ahetawal it's not as easy to access but there is a 5V pin close to the USB ports.

**Comment by ahetawal** [comment]
@johnnyman727 I see pins marked 5VIN and 5V next to USB ports. Comparing to Tessel1, how do I make use of them on T2. 
Apologies for this basic question, this is my first ever board I am working with, so might not be as obvious to use this pin. 
I was not able to find any documentation on these pins as such in terms of usage, happy to help with that, If someone can guide me to how to use them correctly.
Something like this would be really helpful : 
https://github.com/tessel/hardware/blob/master/tessel-hardware-overview.md#gpio-bank

**Comment by johnnyman727** [comment]
For the record, I followed up with @ahetawal on [the forums](https://forums.tessel.io/t/how-to-use-5v-pin-on-tessel2/2348/2).

**Comment by Frijol** [comment]
Hi all, based on https://github.com/tessel/hardware-modules/issues/5 there are a couple of difficulties in getting my PIR module to work as expected on Tessel 2:

- [ ] https://github.com/Frijol/PIR/issues/3, where I wrote checks for T1 specific hardware into the driver - should be a quick fix
- [ ] https://github.com/tessel/t2-firmware/issues/69 this module depends on 'rise' and 'fall' events, which based on this issue are not available on T2 currently due to hardware constraints. It looks like something that can be fixed either on this module or in software on Tessel 2's firmware. Either of those are theoretically pretty easy to do as well. It would be simplest to modify this PIR driver, because based on [this comment](https://github.com/tessel/t2-firmware/issues/69#issuecomment-122600530) the software fix might be a little unreliable. This would not matter much for PIR, since the component is not totally reliable anyway, but the requirements would be stricter for Tessel.

And of course:

- [ ] https://github.com/Frijol/PIR/issues/5 the readme of this module should show how to use it on Tessel 2.

As @davidfekke kindly notes,

1. It is definitely possible to use the PIR hardware with Tessel 2 regardless of this particular software module (though it would be great to fix this one up).
2. I am currently abroad - and actually don't have any hardware with me.

Would someone who does have hardware on hand be up for tackling these issues? I'm happy to review code and re-publish the module. @ahetawal is this something that would be interesting to you?

Thanks,
Kelsey

**Comment by Frijol** [comment]
Apparently [the 'rise' and 'fall' events might already exist](https://github.com/tessel/t2-firmware/issues/69#issuecomment-209330998).

**Comment by ahetawal** [comment]
Happy to help, If I know, how I am suppose to :frowning: 
I am assuming by hardware you mean PIR sensor, I dont have it with me yet, was trying to figure out how will it work before I go buy it, as it will be my first time playing with such boards.
Based on this other [thread](https://forums.tessel.io/t/how-to-use-5v-pin-on-tessel2/2348)

**Comment by Frijol** [comment]
Thanks, makes sense! It would be lovely if you can build/test a way that the PIR module doesn't have to depend on https://github.com/tessel/t2-firmware/issues/69

**Comment by Connor-Knabe** [comment]
I'm wanting to do the same thing. No luck yet. Has anyone else had success?

**Comment by Frijol** [comment]
Fixed! (Finally- sorry that took so long)

**Comment by mbrevda** [comment]
@johnnyman727 any chance you can elaborate on how you get 5v on the t2? The forums seem to be down atm. Thanks!
